---
# template-gh-task: 1.2.0
name: "X_TASK_TITLE_X/X_TARGET_TITLE_X"

env:
  DEV_CICD_DEBUG: ${{ vars.DEV_CICD_DEBUG || 'NONE' }}
  DEV_CICD_DEBUG_BASH: ${{ vars.DEV_CICD_DEBUG_BASH || '' }}
  BL64_LIB_CICD: ${{ vars.BL64_LIB_CICD || 'YES' }}
  DEV_TEST_BASH_RUNNER_ENVIRONMENT: ${{ vars.DEV_TEST_BASH_RUNNER_ENVIRONMENT || 'ON' }}

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "feature/**"
      - "release/**"
    # X_PATHS_PLACEHOLDER_X

jobs:
  X_TASK_X-X_TARGET_X:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Download tools"
        run: |
          ./bin/dev-lib-base &&
          # X_TOOLS_PLACEHOLDER_X

      # X_STEPS_PLACEHOLDER_X
...
